// leave off @2x/@3x
const images = {
  home: require('../Images/Icons/icon-home.png'),
  profile: require('../Images/Icons/icon-profile.png'),
  notifikasi: require('../Images/Icons/icon-notifikasi.png'),
  transaksi: require('../Images/Icons/icon-transaksi.png'),
  homeActive: require('../Images/Icons/icon-homered.png'),
  profileActive: require('../Images/Icons/icon-profilered.png'),
  notifikasiActive: require('../Images/Icons/icon-notifikasired.png'),
  transaksiActive: require('../Images/Icons/icon-transaksired.png'),
  iconBack: require('../Images/Icons/icon-back.png'),
  verified: require('../Images/Icons/icon-verified.png'),
  phone: require('../Images/phone.png'),
  gembok: require('../Images/gembok.png'),
  welcome: require('../Images/welcome.png'),
  facebook: require('../Images/Icons/icon-facebook.png'),
  love: require('../Images/Icons/icon-love.png'),
  logout: require('../Images/Icons/icon-logout.png'),
  saldo: require('../Images/Icons/icon-saldo.png'),
  daftar: require('../Images/Icons/icon-daftar.png'),
  toko: require('../Images/Icons/icon-toko.png'),
  centang: require('../Images/Icons/icon-centang.png'),
  shoppingCart: require('../Images/Icons/icon-shopping-cart.png'),
  searchGrey: require('../Images/Icons/icon-search-grey.png'),
  searchWhite: require('../Images/Icons/icon-search-white.png'),
  komputer: require('../Images/Icons/icon-computer.png'),
  sport: require('../Images/Icons/icon-olahraga.png'),
  kantor: require('../Images/Icons/icon-kantor.png'),
  dapur: require('../Images/Icons/icon-dapur.png'),
  bayi: require('../Images/Icons/icon-bayi.png'),
  audiovideo: require('../Images/Icons/icon-audiovideo.png'),
  rightArrow: require('../Images/Icons/icon-right-arrow.png'),
  leftArrow: require('../Images/Icons/icon-left-arrow.png'),
  slider1: require('../Images/Sliders/slider1.jpg'),
  slider2: require('../Images/Sliders/slider2.jpg'),
  slider3: require('../Images/Sliders/slider3.jpg'),
  contohproduct: require('../Images/contoh-product.jpg'),
  sort: require('../Images/Icons/icon-sorting.png'),
  filter: require('../Images/Icons/icon-filter.png'),
  grid: require('../Images/Icons/icon-grid.png'),
  close: require('../Images/Icons/icon-close.png'),
  email: require('../Images/Icons/icon-email.png')
}

export default images
